# Generated by Django 3.1.6 on 2021-02-16 20:49

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='itw_product_category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='itw_product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('default_price', models.FloatField()),
                ('description', models.CharField(max_length=50)),
                ('deleted', models.BinaryField(default=b'0')),
                ('porduct_category', models.ManyToManyField(to='product.itw_product_category')),
            ],
        ),
    ]
