# Generated by Django 3.1.6 on 2021-02-24 18:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_auto_20210219_1739'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='porduct_category',
            new_name='product_category',
        ),
    ]
