# Generated by Django 3.1.6 on 2021-02-16 20:54

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):
    dependencies = [
        ('order', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itw_order',
            name='date_registered',
            field=models.DateTimeField(default=datetime.datetime(2021, 2, 16, 20, 54, 1, 219897, tzinfo=utc)),
        ),
    ]
