# Generated by Django 3.1.6 on 2021-02-19 11:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ('product', '0001_initial'),
        ('order', '0003_auto_20210216_2154'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itw_order_unit',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order_units',
                                    to='order.itw_order'),
        ),
        migrations.AlterField(
            model_name='itw_order_unit',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order_units',
                                    to='product.itw_product'),
        ),
    ]
