# Generated by Django 3.1.6 on 2021-02-26 07:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0005_auto_20210219_1739'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderunit',
            name='price',
            field=models.FloatField(),
        ),
    ]
